feat: 태그 저장 및 목록 가져오는 기능 추가
memic-graduation/backend pull request #30
Opened 2024-04-29 13:47 UTC by yunhobb

### 😋 작업한 내용
* 태그를 저장하는 기능
   * 태그를 저장하는 과정에서```existsByName```메서드로 태그가 있으면  에러를 던지도록 했습니다.
       * 해당 에러를 서버 내부에러로 생각을 해야할지 or 사용자에게 message로 넘겨줘야 할지 판단의 기준이 궁금합니다.
   * table의  속성중 ```name```을 unique로 변경하였습니다.
* 태그목록을 가져오는 기능 

### 👍 관련 이슈
Resolved : #29

2024-05-02 08:37 UTC, bjgraduation requested changes

2024-05-02 08:37 UTC, bjgraduation commented on src/main/java/com/example/memic/phrase/application/TagService.java
> +    public TagCreateResponse createTag(final TagCreateRequest request) {
transactional 붙여주세요!

2024-05-02 08:37 UTC, bjgraduation commented on src/main/java/com/example/memic/phrase/domain/Tag.java
> +    @Column(name = "name", nullable = false, unique = true)
db의 제약을 어디서 관리할 지 정해봐도 좋을 것 같습니다!~

2024-05-02 08:37 UTC, bjgraduation commented on src/test/java/com/example/memic/phrase/ui/TagIntegrationTest.java
> +                .andExpect(status().isOk())
[데이터 롤백 정책 관련 글](https://blog.ban-life.com/transactional-%EC%97%86%EC%95%A0%EB%A0%A4%EB%8B%A4-%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC%EA%B9%8C%EC%A7%80-%EB%A7%8C%EB%93%A0-%EC%9D%B4%EC%95%BC%EA%B8%B0-5426116036bb) 첨부합니다!

2024-05-05 03:54 UTC, yunhobb commented
flyway 추가하고 보내주신 블로그 참고해 DatabaseCleaner 추가했습니다.😀

2024-05-05 03:54 UTC, yunhobb commented on src/main/java/com/example/memic/phrase/domain/Tag.java
> +    @Column(name = "name", nullable = false, unique = true)
flyway를 추가했습니다!

2024-05-05 05:55 UTC, yunhobb commented on src/main/java/com/example/memic/phrase/domain/Tag.java
> +@Table(name = "tag", uniqueConstraints = {
api 문서를 정리하다보니 tag 목록은 모든 사용자들이 공유를 하면 안될 것 같아 member 별로 구분하도록 했습니다.

`UniqueConstraint`은 db 규약으로 봐서 코드에 추가하는게 아닌 flyway로 관리를 해야할까요?

2024-05-06 10:52 UTC, bjgraduation commented on src/main/java/com/example/memic/phrase/domain/Tag.java
> +@Table(name = "tag", uniqueConstraints = {
엇 저는 태그 자체는 tag 테이블에서 관리하고,  표현에서 태그를 등록할 때에는 phrase_tag 라는 테이블에서 관리할 생각이었습니다. phrase 에는 멤버 id가 있으니 겹치지는 않을 것 같아요!

2024-05-06 11:00 UTC, bjgraduation commented on src/main/java/com/example/memic/phrase/domain/Tag.java
> +@Table(name = "tag", uniqueConstraints = {
<img width="668" alt="스크린샷 2024-05-06 오후 7 59 48" src="https://github.com/memic-graduation/backend/assets/162856964/a3af487f-59f3-4aaf-8e11-1c583234dc89">
phrase 안에 있는 addTag 메서드입니다!

2024-05-06 11:45 UTC, yunhobb commented on src/main/java/com/example/memic/phrase/domain/Tag.java
> +@Table(name = "tag", uniqueConstraints = {
제가 태그 관련 기능이 Notion처럼 흘러가는거라 잘못 생각하고 다음과 같이 구현을 했네요 .. 수정하겠습니다.

2024-05-06 11:56 UTC, yunhobb commented on src/main/java/com/example/memic/phrase/domain/Tag.java
> +@Table(name = "tag", uniqueConstraints = {
수정 했습니다!

2024-05-06 12:09 UTC, poi1649 approved these changes
고생하셨습니다! 표현에 태그 추가하는 기능은 오늘 회의에서 어떻게 할지 상의해보죠!

2024-05-06 13:27 UTC, bjgraduation approved these changes

2024-05-06 13:27 UTC, merged